name: appanimestrue
description: ver animes online.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  curved_navigation_bar: ^0.1.2
  video_player:
  dio: 2.1.0
  flutter_staggered_grid_view: "^0.2.7"

  http: ^0.12.0
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/powered_by.png